IO_BASE    = $0200

IO0        = IO_BASE + $00
IO1        = IO_BASE + $10
IO2        = IO_BASE + $20
IO3        = IO_BASE + $30
IO4        = IO_BASE + $40
IO5        = IO_BASE + $50
IO6        = IO_BASE + $60
IO7        = IO_BASE + $70
IO8        = IO_BASE + $80
IO9        = IO_BASE + $90
IO10       = IO_BASE + $A0
IO11       = IO_BASE + $B0
IO12       = IO_BASE + $C0
IO13       = IO_BASE + $D0
IO14       = IO_BASE + $E0
IO15       = IO_BASE + $F0
